### ISSUE TITLE
New unsolvable problem!!

### ISSUE THREAD

**Issue by yogeswarl** [fani-lab/RePair#25]
So the colbert code is hardcoded in such a way that integers can only be used. But our aol-ia has passage id as alpha-numeric. I don't know how to convert his, and even if I do, I am unsure how to reconvert it to the same alpha numeric. Have you done this before @hosseinfani

**Comment by hosseinfani** [comment]
ask this question in their issue page.
worst case, simply create aolid-2-int and int-2-aolid dictionaries and save it some

**Comment by yogeswarl** [comment]
I solved it. I just removed that line which does asserstion😂
