### ISSUE TITLE
2022 - SIGIR - Can Users Predict Relative Query Effectiveness?

### ISSUE THREAD

**Issue by yogeswarl** [fani-lab/RePair#27]
Title: **Can Users Predict Relative Query Effectiveness?**
Year: 2022 
venue: SIGIR ( Short paper track)
[Link to paper](https://zendelo.github.io/publication/zendel-2022/zendel-2022.pdf)

**Main problem:**
Often users' needs will not be met if their query is not formulated in the right way to retrieve a web page
**Output:**
They compare results generated by a SERP (Search engine results page) to that of a query selected by the user and compare its nDCG@10, showing both have similar end results.
**Contribution and Motivation:**
They used crowd-sourced workers from Amazon's Mechanical Turk for 2 tasks, 
- A query ranking task
- A query rating task

The motivation of this paper is to explore whether users can predict the effectiveness of alternative queries for the same retrieval need and hence provide guidance (or even training data) to automatic techniques for query performance prediction.

**Proposed method:**
given 2 HITs (Human Intelligence tasks): Ranking and rating. Each Worker has to rank/rate a given query for its effectiveness on a scale of 1-5.  This was later compared with that of the retrieval from the SERP, and from the comparison of the results, the discovery is explained.

**Gaps in the work:**
This study was done with the help of crowd workers, which may not be the same with a general community.

Also, they only focused on a limited set of queries from (UQV100 dataset)[https://www.microsoft.com/en-us/research/publication/uqv100-a-test-collection-with-query-variability/]
**code:**
Analysis of the results are available in the repository
https://github.com/Zendelo/cs-qpp

**Comment by hosseinfani** [comment]
@yogeswarl 
thank you. please include this in the paper's related work section.

**Comment by yogeswarl** [comment]
Thank you!.
